config/routes.rb
Rails.application.routes.draw do
   root to: 'employees#index'
   resources :employees do
     resources :divisions
     resources :projects
   end
     end
   

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/division.rb
class Division < ApplicationRecord
  belongs_to :employee
  validates :name, presence: true
   validates_length_of :name, maximum: 100
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :projects, dependent: :destroy
  has_many :divisions, dependent: :destroy
  validates :name, presence: true
  validates_length_of :name, maximum: 100
  before_save(:titleize_employee)
  scope :search, -> (employee_parameter) { where("name like ?", "%#{employee_parameter}%")} 

  private
  def titleize_employee
    self.name = self.name.titleize
  end
end

def self.rock
  where(name: "Rock")
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :employee
  validates :name, presence: true
   validates_length_of :name, maximum: 100
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/divisions_controller.rb
class DivisionsController < ApplicationController

  def index
    @divisions = Division.all
    render :index
  end
  def new
    @employee = Employee.find(params[:employee_id])
    @division = @employee.divisions.new
    render :new
  end

  def create
    @employee = Employee.find(params[:employee_id])
    @division = @employee.divisions.new(division_params)
    if @division.save
      redirect_to employee_path(@employee)
    else
      render :new
    end
  end



  def edit
  @employee = Employee.find(params[:employee_id])
  @division = Division.find(params[:id])
  render :edit
end

  def show
    @employee = Employee.find(params[:employee_id])
    @division = Division.find(params[:id])
    render :show
  end

  def update
  @division = Division.find(params[:id])
  if @division.update(division_params)
    redirect_to employee_path(@division.employee)
  else
    render :edit
  end
end

def destroy
  @division = Division.find(params[:id])
  @division.destroy
  redirect_to employee_path(@division.employee)
end

  private
    def division_params
      params.require(:division).permit(:name)
    end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

  def index
    if params[:search]
      @employees = Employee.search(params[:search])
    else params[:id]
    @employees = Employee.all
    render :index
  end
end

  def new
    @employee = Employee.new
    render :new
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      flash[:notice] = "Employee successfully added!"
      redirect_to employees_path
    else
      render :new
    end
  end

  def edit
    @employee = Employee.find(params[:id])
    render :edit
  end

  def show
      @employee = Employee.find(params[:id])
    render :show
  end

  def update
    @employee= Employee.find(params[:id])
    if @employee.update(employee_params)
      redirect_to employees_path
    else
      render :edit
    end
  end

  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy
    redirect_to employees_path
  end

  private
  def employee_params
    params.require(:employee).permit(:name)
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.all
    render :index
  end

  def new
    @employee = Employee.find(params[:employee_id])
    @project = @employee.projects.new
    render :new
  end

  def create
    @employee = Employee.find(params[:employee_id])
    @project = @employee.projects.new(project_params)
    if @project.save
      redirect_to employee_path(@employee)
    else
      render :new
    end
  end

  def edit
    @employee = Employee.find(params[:employee_id])
    @project = Project.find(params[:id])
    render :edit
  end

  def show
    @employee = Employee.find(params[:employee_id])
    @project = Project.find(params[:id])
    render :show
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      redirect_to employee_path(@project.employee)
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to employee_path(@project.employee)
  end

  private
  def project_params
    params.require(:project).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/divisions/edit.html.erb
<h1>Edit division:</h1>

<%= form_for [@employee, @division] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <p><%= f.submit %></p>
<% end %>

app/views/divisions/new.html.erb
<h1>Add a new division:</h1>

<%= render "layouts/division_form" %>

app/views/divisions/show.html.erb
<h1>Division: <%= @division.name %></h1>
<h2>Employee: <%= @employee.name %></h2>

<p><%= link_to "Edit division", edit_employee_division_path(@employee, @division) %></p>
<p><%= link_to "Delete division", employee_division_path(@employee, @division),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>

<p><%= link_to "Return to employee", employee_path(@employee) %></p>

app/views/employees/edit.html.erb
<h1>Edit employee</h1>

<%= form_for @employee do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit  %>
<% end %>

app/views/employees/index.html.erb
<h1>Employees</h1>
<form>
  <label for="Search by name">Search by employee name:</label>
  <input type="text" name="search" >
  <button type="submit" name="button">go</button>
</form>

<% if @employees.any? %>
  <ul>
    <% @employees.each do |employee| %>
      <li><%= link_to employee.name, employee_path(employee) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no employees yet.</p>
<% end %>


<p><%= link_to "Create new employee", new_employee_path %></p>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render "layouts/employee_form" %>

app/views/employees/show.html.erb
<h1><%= @employee.name %></h1>


<% if @employee.divisions.any? %>
  <h4>Here are the divisions for this employee:</h4>

  <% @employee.divisions.each do |division| %>
    <ul>
      <li>
        <%= link_to division.name, employee_division_path(@employee, division) %>
      </li>
    </ul>
  <% end %>
<% else %>
  <p>No divisions are listed for this employee.</p>
<% end %>

<p><%= link_to "Add a division", new_employee_division_path(@employee) %></p>

<% if @employee.projects.any? %>
  <h4>Here are the projects for this employee:</h4>

  <% @employee.projects.each do |project| %>
    <ul>
      <li>
        <%= link_to project.name, employee_project_path(@employee, project) %>
      </li>
    </ul>
  <% end %>
<% else %>
  <p>No projects are listed for this employee.</p>
<% end %>

<p><%= link_to "Add a project", new_employee_project_path(@employee) %></p>

<p><%= link_to "Edit", edit_employee_path(@employee) %></p>
<p><%= link_to "Delete employee", employee_path(@employee),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>

<p><%= link_to "Return to employees", employees_path %></p>

app/views/layouts/_division_form.html.erb
<%= render "layouts/errors", :object => @division %>

<%= form_for [@employee, @division] do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<p><%= f.submit %></p>
<% end %>

app/views/layouts/_employee_form.html.erb
<%= render "layouts/errors", :object => @employee %>
<%= form_for @employee do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.submit  %>
<% end %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_project_form.html.erb
<%= render "layouts/errors", :object => @project %>

<%= form_for [@employee, @project] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <p><%= f.submit %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsEmployeeTrackerNew</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= flash[:alert] %>
  <%= flash[:notice] %>
  <%= yield %>
</body>
</html>

app/views/projects/edit.html.erb
<h1>Edit project:</h1>

<%= form_for [@employee, @project] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <p><%= f.submit %></p>
<% end %>

app/views/projects/new.html.erb
<h1>Add a new project:</h1>

<%= render "layouts/project_form" %>

app/views/projects/show.html.erb
<h1>Project: <%= @project.name %></h1>
<h2>Employee: <%= @employee.name %></h2>


<p><%= link_to "Edit project", edit_employee_project_path(@employee, @project) %></p>
<p><%= link_to "Delete project", employee_project_path(@employee, @project),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>

<p><%= link_to "Return to employee", employee_path(@employee) %></p>